package project;
import javax.swing.*;
import javax.swing.border.*;
import java.awt.*;
import java.util.Calendar;
import java.util.Date;

public class FacultyDashboard extends JPanel {
    private SmartAttendanceApp mainApp;
    private JLabel codeDisplay;
    private JSpinner dateSpinner;
    private JComboBox<String> subjectCombo;

    public FacultyDashboard(SmartAttendanceApp app) {
        this.mainApp = app;
        setLayout(new BorderLayout());
        setBackground(new Color(230, 235, 230));

        // --- TOP HEADER SECTION ---
        JPanel headerPanel = new JPanel(new BorderLayout());
        headerPanel.setBackground(new Color(10, 60, 40));
        headerPanel.setPreferredSize(new Dimension(800, 100));
        headerPanel.setBorder(BorderFactory.createMatteBorder(0, 0, 5, 0, new Color(180, 150, 70)));

        JPanel titleGroup = new JPanel(new GridLayout(2, 1));
        titleGroup.setOpaque(false);
        titleGroup.setBorder(new EmptyBorder(10, 20, 10, 0));
        JLabel mainTitle = new JLabel("Smart Attendance Management System");
        mainTitle.setFont(new Font("Serif", Font.BOLD, 22));
        mainTitle.setForeground(Color.WHITE);
        JLabel subTitle = new JLabel("FACULTY CONTROL PANEL");
        subTitle.setFont(new Font("SansSerif", Font.PLAIN, 14));
        subTitle.setForeground(new Color(200, 200, 200));
        titleGroup.add(mainTitle);
        titleGroup.add(subTitle);
        headerPanel.add(titleGroup, BorderLayout.WEST);

        JPanel rightHeaderGroup = new JPanel(new FlowLayout(FlowLayout.RIGHT, 15, 30));
        rightHeaderGroup.setOpaque(false);

        SpinnerDateModel dateModel = new SpinnerDateModel(new Date(), null, null, Calendar.DAY_OF_MONTH);
        dateSpinner = new JSpinner(dateModel);
        JSpinner.DateEditor editor = new JSpinner.DateEditor(dateSpinner, "dd/MM/yyyy");
        dateSpinner.setEditor(editor);
        dateSpinner.setPreferredSize(new Dimension(110, 25));

        JButton profileBtn = new JButton("👤");
        profileBtn.setFont(new Font("Segoe UI Emoji", Font.PLAIN, 18));
        profileBtn.setBackground(new Color(180, 150, 70));
        profileBtn.setForeground(Color.WHITE);
        profileBtn.setFocusPainted(false);
        profileBtn.addActionListener(e -> showProfileInfo());

        rightHeaderGroup.add(new JLabel("Date: ") {{ setForeground(Color.WHITE); }});
        rightHeaderGroup.add(dateSpinner);
        rightHeaderGroup.add(profileBtn);
        headerPanel.add(rightHeaderGroup, BorderLayout.EAST);

        JPanel subHeader = new JPanel(new FlowLayout(FlowLayout.LEFT, 20, 5));
        subHeader.setBackground(new Color(7, 45, 30));
        String[] subjects = {"Java Programming", "Computer Network", "Web Based programming", "Electronic Commerce", "Statistics","laboratory Course"};
        subjectCombo = new JComboBox<>(subjects);
        subjectCombo.setBackground(new Color(10, 60, 40));
        subjectCombo.setForeground(Color.WHITE);

        subHeader.add(new JLabel("Subject: ") {{ setForeground(Color.WHITE); }});
        subHeader.add(subjectCombo);

        JPanel topContainer = new JPanel(new BorderLayout());
        topContainer.add(headerPanel, BorderLayout.NORTH);
        topContainer.add(subHeader, BorderLayout.SOUTH);
        add(topContainer, BorderLayout.NORTH);

        // --- CENTER ---
        JPanel mainContainer = new JPanel(new GridBagLayout());
        mainContainer.setOpaque(false);

        JPanel card = new JPanel();
        card.setLayout(new BoxLayout(card, BoxLayout.Y_AXIS));
        card.setBackground(Color.WHITE);
        card.setBorder(BorderFactory.createCompoundBorder(
            new LineBorder(new Color(180, 150, 70), 1),
            new EmptyBorder(20, 40, 20, 40)
        ));

        JLabel cardTitle = new JLabel("Generate Attendance");
        cardTitle.setAlignmentX(Component.CENTER_ALIGNMENT);
        cardTitle.setFont(new Font("SansSerif", Font.BOLD, 18));
        cardTitle.setForeground(new Color(10, 60, 40));

        JButton genBtn = createStyledButton("GENERATE CODE");

        codeDisplay = new JLabel(" ", JLabel.CENTER);
        codeDisplay.setFont(new Font("Monospaced", Font.BOLD, 28));
        codeDisplay.setForeground(new Color(150, 50, 50));
        codeDisplay.setPreferredSize(new Dimension(250, 60));
        codeDisplay.setBorder(BorderFactory.createLineBorder(new Color(220, 220, 220)));
        codeDisplay.setAlignmentX(Component.CENTER_ALIGNMENT);

        JButton viewBtn = createStyledButton("VIEW ATTENDENCE");
        viewBtn.addActionListener(e -> showAttendanceRecords());

        
        genBtn.addActionListener(e -> {

            String subject = (String) subjectCombo.getSelectedItem();

           // generated by  db and connect direct
            String generatedCode = DbConnect.generateCode(subject);

            codeDisplay.setText(generatedCode);

            //  memory update
            SmartAttendanceApp.currentActiveCode = generatedCode;
            SmartAttendanceApp.activeSubject = subject;

            JOptionPane.showMessageDialog(this, "Code Generated & Saved in Database!");
        });

        card.add(cardTitle);
        card.add(Box.createRigidArea(new Dimension(0, 20)));
        card.add(genBtn);
        card.add(Box.createRigidArea(new Dimension(0, 15)));
        card.add(codeDisplay);
        card.add(Box.createRigidArea(new Dimension(0, 15)));
        card.add(viewBtn);

        mainContainer.add(card);
        add(mainContainer, BorderLayout.CENTER);

        JPanel footer = new JPanel();
        footer.setOpaque(false);
        footer.setBorder(new EmptyBorder(0, 0, 30, 0));
        JButton logoutBtn = createStyledButton("Logout");
        logoutBtn.addActionListener(e -> mainApp.switchPage("Login"));
        footer.add(logoutBtn);
        add(footer, BorderLayout.SOUTH);
    }

    private void showAttendanceRecords() {

        String subject = (String) subjectCombo.getSelectedItem();

        java.util.List<String[]> records = DbConnect.getAttendanceBySubject(subject);

        if (records.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No attendance found!");
            return;
        }

        String[] columns = {"Student Name", "Subject", "Date & Time"};
        Object[][] data = new Object[records.size()][3];

        for (int i = 0; i < records.size(); i++) {

            data[i][0] = records.get(i)[0]; // student
            data[i][1] = records.get(i)[1]; // subject
            data[i][2] = records.get(i)[2]; // date
        }

        JTable table = new JTable(data, columns);

        int totalStudents = DbConnect.getTotalStudentsBySubject(subject);
        int present = records.size();
        int absent = totalStudents - present;

        JPanel panel = new JPanel(new BorderLayout());
        panel.add(new JScrollPane(table), BorderLayout.CENTER);

        JLabel summary = new JLabel(
                "Total Students: " + totalStudents +
                "   Present: " + present +
                "   Absent: " + absent
        );

        panel.add(summary, BorderLayout.SOUTH);

        JOptionPane.showMessageDialog(this, panel, "Attendance Records", JOptionPane.INFORMATION_MESSAGE);
    }
    private void showProfileInfo() {
        String facultyName = SmartAttendanceApp.loggedInFacultyName;
        String selectedSubject = (String) subjectCombo.getSelectedItem();
        String selectedDate = ((JSpinner.DateEditor)dateSpinner.getEditor()).getFormat().format(dateSpinner.getValue());

        String message = String.format("Faculty Name: %s\nSubject: %s\nSelected Date: %s",
                facultyName, selectedSubject, selectedDate);

        JOptionPane.showMessageDialog(this, message, "Faculty Profile", JOptionPane.INFORMATION_MESSAGE);
    }

    private JButton createStyledButton(String text) {
        JButton btn = new JButton(text);
        btn.setFont(new Font("SansSerif", Font.BOLD, 14));
        btn.setBackground(new Color(10, 60, 40));
        btn.setForeground(Color.WHITE);
        btn.setFocusPainted(false);
        btn.setAlignmentX(Component.CENTER_ALIGNMENT);
        btn.setMaximumSize(new Dimension(200, 40));
        btn.setCursor(new Cursor(Cursor.HAND_CURSOR));
        return btn;
    }
}